#include <Arduino.h>

/* Main.ino file generated by New Project wizard
 *
 * Created:   jue. feb. 26 2026
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")


#pragma GCC pop_options

// Peripheral Constructors

void peripheral_setup () {
}

void peripheral_loop() {
}
//---CONFIG_END---
byte ledPin1 = 3;
byte ledPin2 = 5;
int tiempoEncendido = 200;
uint16_t tiempoApagado = 800;

void setup () {
peripheral_setup();
 pinMode(ledPin1, OUTPUT);
 pinMode(ledPin2, OUTPUT);
// TODO: put your setup code here, to run once:
}

void loop() {
peripheral_loop();
digitalWrite(ledPin1, HIGH);
digitalWrite(ledPin2, LOW);
delay(300);

digitalWrite(ledPin1, LOW);
digitalWrite(ledPin2, HIGH);
  delay(700);
// TODO: put your main code here, to run repeatedly:
}

}