/* Main.ino file generated by New Project wizard
 *
 * Created:   mar. feb. 24 2026
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

#include <Arduino.h>

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")


#pragma GCC pop_options

// Peripheral Constructors

void peripheral_setup () {
}

void peripheral_loop() {
}
//---CONFIG_END---

int ledPin = 3;
int onTime = 200;
int offTime = 800;

void setup() {
  peripheral_setup();  
  pinMode(ledPin, OUTPUT);
}

void loop() {
  peripheral_loop();  
  digitalWrite(ledPin, HIGH);
  delay(onTime);
  digitalWrite(ledPin, LOW);
  delay(offTime);
}
